parameters:
    api.request_listener.class: AppBundle\EventListener\RequestListener
    api.controller_response_listener.class: AppBundle\EventListener\ControllerResponseListener
    api.event_listener.socket.room.class: AppBundle\EventListener\Socket\RoomListener
    api.event_listener.socket.pm.class: AppBundle\EventListener\Socket\PMListener
    api.event_subscriber.socket.class: AppBundle\EventListener\Socket\SocketSubscriber
    api.exception_listener.class: AppBundle\EventListener\ExceptionListener
    app.events.user_action_subscriber.class: AppBundle\EventListener\UserEventSubscriber
    app.playlist.rngmod.class: AppBundle\Playlist\RngMod

services:
    encoder_json:
      class: Symfony\Component\Serializer\Encoder\JsonEncoder

    normalizer_object:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    serializer_json:
      class: Symfony\Component\Serializer\Serializer
      arguments:
        - ["@normalizer_object"]
        - ["@encoder_json"]

    ## ########################################################################
    ## Session
    ## ########################################################################
    app.session.handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\WriteCheckSessionHandler
        arguments:
            - "@snc_redis.session.handler"

    ## ########################################################################
    ## Mutex Playlist
    ## ########################################################################
    app_mutex_playlist:
      class: malkusch\lock\mutex\PredisMutex
      arguments:
        - ["@snc_redis.default"]
        - "playlist"
        - 15

    ## ########################################################################
    ## API Request Listener
    ## ########################################################################
    api.request_listener:
        class: "%api.request_listener.class%"
        arguments:
          - "@serializer_json"
          - "@normalizer_object"
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ## ########################################################################
    ## API Controller Response Listener
    ## ########################################################################
    api.controller_response_listener:
        class: "%api.controller_response_listener.class%"
        arguments:
          - "@serializer_json"
          - "@normalizer_object"
        tags:
          - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    ## ########################################################################
    ## API Exception Listener
    ## ########################################################################
    api.exception_listener:
        class: "%api.exception_listener.class%"
        arguments:
          - "@serializer_json"
          - "@normalizer_object"
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ## ########################################################################
    ## User Event Subscriber
    ## ########################################################################
    app.events.user_event_subscriber:
      class: "%app.events.user_action_subscriber.class%"
      arguments:
        - "@doctrine.orm.entity_manager"
      tags:
        - { name: kernel.event_subscriber }

    ## ########################################################################
    ## Registration Listener
    ## ########################################################################
    app.registration_complet:
      class: AppBundle\Listener\RegistrationListener
      arguments:
        - "@app.service.thumbs"
      tags:
        - { name: kernel.event_subscriber }

    ## ########################################################################
    ## Socket Room Listener
    ## ########################################################################
    api.event_listener.socket.room:
        class: "%api.event_listener.socket.room.class%"
        arguments:
          - "@event_dispatcher"
          - "@doctrine.orm.default_entity_manager"
          - "@monolog.logger"

    ## ########################################################################
    ## Socket PM Listener
    ## ########################################################################
    api.event_listener.socket.pm:
        class: "%api.event_listener.socket.pm.class%"
        arguments:
          - "@event_dispatcher"
          - "@doctrine.orm.default_entity_manager"
          - "@monolog.logger"

    ## ########################################################################
    ## Socket Subscriber
    ## ########################################################################
    api.event_subscriber.socket:
        class: "%api.event_subscriber.socket.class%"
        calls:
          - [setRoomListener, ["@api.event_listener.socket.room"]]
          - [setPMListener, ["@api.event_listener.socket.pm"]]
        tags:
          - { name: kernel.event_subscriber }

    ## ########################################################################
    ## YouTube Service
    ## ########################################################################
    madcoda.youtube.youtube:
      class: Madcoda\Youtube\Youtube
      arguments:
        - { key: "%app_service_youtube_api_key%" }
      calls:
        - [setReferer, ["%app_url%"]]

    ## ########################################################################
    ## Video Info Service
    ## ########################################################################
    app.service.video:
      class: AppBundle\Service\VideoService
      arguments:
        - "%app_service_video_params%"
        - "@monolog.logger"
      calls:
        - [setYoutube, ["@madcoda.youtube.youtube"]]

    ## ########################################################################
    ## Thumbs Service
    ## ########################################################################
    app.service.thumbs:
      class: AppBundle\Service\ThumbsService
      arguments:
        - "@app.identicon"
        - "@app.service.upload"
        - "%app_service_thumbs_params%"

    ## ########################################################################
    ## Upload Service
    ## ########################################################################
    app.service.upload:
      class: AppBundle\Service\UploadService
      arguments:
        - "@aws.s3"
        - "@=service('doctrine').getRepository('AppBundle:Upload')"
        - "%aws_buckets%"
        - "%app_service_upload_rooturl%"
      calls:
        - [setLogger, ["@logger"]]

    ## ########################################################################
    ## Registration Form
    ## ########################################################################
    app.form.registration:
      class: AppBundle\Form\RegistrationType
      tags:
        - { name: form.type, alias: registration }

    ## ########################################################################
    ## RabbitMQ Save Video Consumer
    ## ########################################################################
    app_rabbitmq_save_video_consumer:
      class: AppBundle\RabbitMQ\Consumer\SaveVideoConsumer
      arguments:
        - "@service_container"

    ## ########################################################################
    ## Sitemap Event Listeners
    ## ########################################################################
    app.sitemap.playlist_subscriber:
      class:     AppBundle\EventListener\SitemapPlaylistSubscriber
      arguments:
        - "@router"
        - "@doctrine.orm.entity_manager"
      tags:
        - { name: "kernel.event_subscriber", priority: 100 }

    ## ########################################################################
    ## Playlist Providers
    ## ########################################################################
    app.playlist.providers:
      class: AppBundle\Playlist\Providers

    ## ########################################################################
    ## Identicon
    ## ########################################################################
    app.identicon:
      class: Identicon\Identicon

    ## ########################################################################
    ## RNGMod
    ## ########################################################################
    app.playlist.rngmod:
      class: "%app.playlist.rngmod.class%"
      arguments:
        - "@=service('doctrine').getRepository('AppBundle:VideoLog')"
